name: amhello
version: 0.1
vendor: Shawn wang <shawn.wang@canonical.com>
summary: A autotools-project snapcraft example. Hello World.
description:
 This is a automake example from.
 https://www.gnu.org/software/automake/manual/html_node/Creating-amhello.html
icon: icon.png

parts:
  hello:
    type: autotools-project
    plugin: autotools
    source: .
    configflags:
        - --enable-static
        - --enable-shared
        - --disable-manual
    snap:
        - -bin
